baseURL = "sad-elion-2cdadb.netlify.app"
disqusShortname = ""
googleAnalytics = "UA-180884863-1"
languageCode = "es-Es"
languageName = "Es"
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Googleate"
[markup.goldmark.renderer]
unsafe = true
[[menu.company]]
URL = "#"
name = "Quick Start"
weight = 1
[[menu.company]]
URL = "https://www.googleate.es/blog/post-2/"
name = "Acerca de"
weight = 2
[[menu.product]]
URL = "https://www.googleate.es/pricing/"
name = "Tarifas y precios"
weight = 1
[[menu.support]]
URL = "faq"
name = "Preguntas Frecuentes"
weight = 1
[[menu.support]]
URL = "terms-conditions"
name = "Términos y condiciones legales"
weight = 2
[[menu.support]]
URL = "privacy-policy"
name = "Política de privacidad"
weight = 3
[params]
author = "Santiago Llera"
contact_form_action = "https://www.googleate.es/contact/"
copyright = "© Googleate 2020"
description = "Googleate, marketing digital, marbella, vender en internet, paginas web"
footer_content = "Googléate es la única agencia de publicidad online que garantiza el primer puesto en Google"
logo = "images/logo.png"
logo_width = "200px"
social = []
[params.navigation_button]
enable = true
label = "Contacto"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[params.preloader]
enable = true
preloader = ""
